# Generated by Django 5.2.4 on 2025-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(db_index=True, max_length=100)),
                (
                    "type_of_holiday",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_accommodation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
