# Generated by Django 5.2.4 on 2025-07-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hotels",
            new_name="Hotel",
        ),
    ]
