# Generated by Django 5.2.4 on 2025-08-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_rename_hotels_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeAccommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel", models.BooleanField(default=False, verbose_name="Отель")),
                ("hostel", models.BooleanField(default=False, verbose_name="Хостел")),
                ("villa", models.BooleanField(default=False, verbose_name="Вилла")),
                (
                    "apartments",
                    models.BooleanField(default=False, verbose_name="Апартаменты"),
                ),
                (
                    "guest_house",
                    models.BooleanField(default=False, verbose_name="Гостевой дом"),
                ),
                (
                    "hotel_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
                    ),
                ),
            ],
        ),
    ]
