# Generated by Django 5.2.4 on 2025-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_food",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
