# Generated by Django 5.2.4 on 2025-08-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("type_of_food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListFoodTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "without_food",
                    models.BooleanField(default=False, verbose_name="Без питания"),
                ),
                (
                    "breakfast",
                    models.BooleanField(default=False, verbose_name="Завтрак"),
                ),
                (
                    "breakfast_and_dinner",
                    models.BooleanField(default=False, verbose_name="Завтрак и ужин"),
                ),
                (
                    "full_board",
                    models.BooleanField(default=False, verbose_name="Полный пансион"),
                ),
                (
                    "all_inclusive",
                    models.BooleanField(default=False, verbose_name="All inclusive"),
                ),
                (
                    "ultra_all_inclusive",
                    models.BooleanField(
                        default=False, verbose_name="Ultra All inclusive"
                    ),
                ),
                (
                    "type_of_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="type_of_food.typefood",
                    ),
                ),
            ],
        ),
    ]
