# Generated by Django 5.2.4 on 2025-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_food",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("adults_living", models.PositiveIntegerField(blank=True, null=True)),
                ("children_living", models.PositiveIntegerField(blank=True, null=True)),
                ("area", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "number_of_rooms_category",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
