# Generated by Django 5.2.4 on 2025-08-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListCategoryRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard",
                    models.BooleanField(default=False, verbose_name="Standard"),
                ),
                (
                    "single_room",
                    models.BooleanField(default=False, verbose_name="Single Room"),
                ),
                (
                    "double_room",
                    models.BooleanField(default=False, verbose_name="Double Room"),
                ),
                (
                    "twin_room",
                    models.BooleanField(default=False, verbose_name="Twin Room"),
                ),
                (
                    "triple_room",
                    models.BooleanField(default=False, verbose_name="Triple Room"),
                ),
                (
                    "family_room",
                    models.BooleanField(default=False, verbose_name="Family Room"),
                ),
                (
                    "superior_room",
                    models.BooleanField(default=False, verbose_name="Superior Room"),
                ),
                (
                    "deluxe_room",
                    models.BooleanField(default=False, verbose_name="Deluxe Room"),
                ),
                ("studio", models.BooleanField(default=False, verbose_name="Studio")),
                ("suite", models.BooleanField(default=False, verbose_name="Suite")),
                (
                    "junior_suite",
                    models.BooleanField(default=False, verbose_name="Junior Suite"),
                ),
                (
                    "residence",
                    models.BooleanField(default=False, verbose_name="Residence"),
                ),
                (
                    "royal_suite",
                    models.BooleanField(default=False, verbose_name="Royal Suite"),
                ),
                (
                    "penthouse",
                    models.BooleanField(default=False, verbose_name="Penthouse"),
                ),
                (
                    "room_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_rooms.hotelroom",
                    ),
                ),
            ],
        ),
    ]
